# fly.toml app configuration file generated for patrol-simulator-backend-test on 2023-08-08T01:02:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "patrol-simulator-backend-test"
primary_region = "scl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
